### ISSUE TITLE
Visualització pàgina de cursos 

### ISSUE THREAD

**Issue by XaviFibla** [PymeraliaProject-Sprint-4/Pymeshield-Sprint-6#55]
A la pàgina de cursos com administrador les targetes dels cursos surten tallades.
https://pymeshield.ebrehosting.asix2.iesmontsia.cat/course/client

A més quan passes el ratolí per sobre no surt la "maneta" indicant que és pot clickar

**Comment by francisco-zr** [comment]
arreglado por @ivansorribes
