### ISSUE TITLE
No és pot actualitzar la imatge del perfil

### ISSUE THREAD

**Issue by XaviFibla** [PymeraliaProject-Sprint-4/Pymeshield-Sprint-6#64]
Al intentar pujar una imatge editant el perfil com a client em surt pàgina d'error

**Comment by Tud0r420** [comment]
He canviat la imatge d'un client per un altra, he tancat sessió i he tornat a entrar i no experimento cap error.

**Comment by francisco-zr** [comment]
Fixed por @Sergi-Fornos-Gonzalez
